### ISSUE TITLE
What browsers to test?

### ISSUE THREAD

**Issue by phillipj** [janl/mustache.js#450]
Any thoughts about which browsers and their specific version we should run tests on?

We initially tried to run tests on 25 different browser versions, but reduced it to latest chrome and firefox because it took 15-25 minutes to run.

These were the 25 we had at the beginning:
```yaml
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: 6..latest
  - name: opera
    version: 11..latest
  - name: ie
    version: 8..latest
  - name: iphone
    version: 6.0..latest
  - name: android
    version: 4.0..latest 
```
